version: "3.8"
networks:
  mojaloop-net:
    name: mojaloop-net


services:
  core-connector:
    image: dfsp-core-connector:Release
    networks:
      - mojaloop-net
    env_file: .env
    ports:
      - "3003:3003"
      - "3004:3004"
